### ISSUE TITLE
增量训练的原理

### ISSUE THREAD

**Issue by dengxiaocai** [Gao-Chengzhi/incremental-object-detection-based-on-mmdetection#1]
你好，这里使用到的增量训练原理是啥，mmdet源码改动的地方有哪些？

**Comment by Gao-Chengzhi** [comment]
就是一个很简单的小样本微调，先在基类上训练一个基础模型，之后在新类训练时扩展分类头维度，使用基类和新类（数据回放）每类k张图片（小样本）进行微调。
关于源码改动，所有有修改的文件都在readme里面提过了，可以git clone之后打开提到的文件查看注释，也可以跟mmdet源码对比一下就知道那里改动了。如果还有问题欢迎询问。

**Comment by dengxiaocai** [comment]
好的，十分感谢
